### ISSUE TITLE
import databasse error

### ISSUE THREAD

**Issue by wpzzz** [Stormiix/converter-api#9]
ERROR 1067 (42000) at line 32: Invalid default value for 'created_at'

**Comment by Stormiix** [comment]
I've tested the same SQL on a new database, and it worked perfectly..
I think this problem is more related to your MYSQL configuration (I'm not a specialist tho xD).
I made a couple of changes to the SQL (Inspired by common answers on StackOverflow) and it still works :  
![2017-12-22 12_45_46-](https://user-images.githubusercontent.com/18377687/34298660-c5dcb35e-e716-11e7-8a06-eda4a1b7b188.png)

Check the last commit.

**Comment by wpzzz** [comment]
`created_at` datetime DEFAULT current_timestamp(),  error
  `created_at` TIMESTAMP DEFAULT NOW(), fine

**Comment by Stormiix** [comment]
Change it if you want ;)
